name 'gravity-platform'
version '0.3.0-dev'

author 'Lucas S. Bickel'
license 'GPL3+'
project_page 'https://github.com/gravity-platform/puppet-gravity'
source 'https://github.com/gravity-platform/puppet-gravity.git'
dependency 'stahnma/epel', '>=0.0.5'
dependency 'puppetlabs/mongodb', '>=0.3.0'
dependency 'kemra102/ius', '>=0.1.0'
