name 'gravity-platform'
version '0.2.0'

author 'Lucas S. Bickel'
license 'GPL3+'
project_page 'https://github.com/gravity-platform/puppet-gravity'
source 'https://github.com/gravity-platform/puppet-gravity.git'
dependency 'purplehazech/syslogng', '>=0.1.1'
dependency 'stahnma/epel', '>=0.0.5'
dependency 'puppetlabs/apache', '>=0.9.0'
dependency 'puppetlabs/firewall', '>=0.4.2'
dependency 'puppetlabs/mongodb', '>=0.3.0'
dependency 'hairmare/hairmareyumrepo', '>=0.1.1'
